# This is a basic workflow to help you get started with Actions

name: CI scheduled - 2h

# Controls when the workflow will run
on:
  schedule:
    - cron:  '18 0/2 * * *'
    - cron:  '18 0/4 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        cid: [0, 2]
    env:
      CHAT_ID: ${{ secrets[format('TELEGRAM_TO_{0}', matrix.cid)] }}
    timeout-minutes: 20

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3.1.2
        with:
          # Version range or exact version of a Python version to use, using SemVer's version range syntax.
          python-version: '3.x'
          # Used to specify a package manager for caching in the default directory. Supported values: pip, pipenv, poetry.
          cache: pip
          # Used to specify the path to dependency files. Supports wildcards or a list of file names for caching multiple dependencies.
          cache-dependency-path: '**/requires.txt'

      - name: Install Dependencies
        run: pip install -r bocfx.egg-info/requires.txt

      - name: Run Main App Quick Update
        if: github.event.schedule == '18 0/2 * * *'
        run: python bocfx/__main__.py -p -t 1 -o output

      - name: Send Photo Message Quick
        if: github.event.schedule == '18 0/2 * * *'
        uses: appleboy/telegram-action@master
        with:
          to: ${{ env.CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: 两小时推送来啦，中行现汇买入价（1天涨跌）
          photo: tests/github.png
          document: output/*.png

      - name: Run Main App Daily Update
        if: github.event.schedule == '18 0/4 * * *'
        run: python bocfx/__main__.py -p -t 21 -o output

      - name: Send Photo Message Daily
        if: github.event.schedule == '18 0/4 * * *'
        uses: appleboy/telegram-action@master
        with:
          to: ${{ env.CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: 四小时推送来啦，中行现汇买入价（21天涨跌）
          photo: tests/github.png
          document: output/*.png

      - name: Run Main App Quick Update
        if: github.event_name == 'workflow_dispatch'
        run: python bocfx/__main__.py -p -t 1 -o output

      - name: Send Photo Message Quick
        if: github.event_name == 'workflow_dispatch'
        uses: appleboy/telegram-action@master
        with:
          to: ${{ env.CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: 手动推送来啦，中行现汇买入价（1天涨跌）
          photo: tests/github.png
          document: output/*.png
      
      - name: Run Main App Daily Update
        if: github.event_name == 'workflow_dispatch'
        run: python bocfx/__main__.py -p -t 21 -o output

      - name: Send Photo Message Daily
        if: github.event_name == 'workflow_dispatch'
        uses: appleboy/telegram-action@master
        with:
          to: ${{ env.CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: 四小时推送来啦，中行现汇买入价（21天涨跌）
          photo: tests/github.png
          document: output/*.png

      - uses: actions/checkout@master
